### ISSUE TITLE
Rewrite the code to clean PIRLS data

### ISSUE THREAD

**Issue by nguyentr17** [yuqiliao/InternationalAssessment_MachineLearning#1]
- [x] Missing rule
- [x] Recode plausible values to achievement level dummy variables
- [x] Choose student and teacher variables (using `grepl`) Line 40-45

**Comment by nguyentr17** [comment]
@yuqiliao Why do we use `asribm01` which is on scale 1-5 for Y? Can we not use `rrea` and then average it and get achievementLevel?

**Comment by yuqiliao** [comment]
that's an option! I did that simply to follow the TIMSS paper. In the TIMSS/PIRLS, besides 5 PV, the datasets also provide 5 proficiency levels (such as `asribm01`) based on 5 PVs, i thought maybe it is "more correct" to use these 5 proficiency levels. you are right, we could totally do what you said.
