### ISSUE TITLE
Write up metric to evaluate models

### ISSUE THREAD

**Issue by nguyentr17** [yuqiliao/InternationalAssessment_MachineLearning#3]
Example for comparison: http://medianetlab.ee.ucla.edu/papers/ICMLWS3.pdf

**Comment by nguyentr17** [comment]
@yuqiliao Can you create a google doc for the proposal?

**Comment by yuqiliao** [comment]
Sure, feel free to edit!

https://docs.google.com/document/d/1uDEnpuPAkI3UcaUqi6oyE0ltR1ovnxig3M3FBpV5q6Q/edit?usp=sharing
